### ISSUE TITLE
Multi-Viewer: Mobile

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#110]
The multi-viewer is wonky on mobile. You can not slide side to side to see text when it goes out of the pane, and text than should all be the same size renders at multiple sizes. For the latter, see the attached screen shot, where the text shifts from big to small on one page.

![img_4411](https://cloud.githubusercontent.com/assets/12518623/20502779/99472390-b037-11e6-8fdd-23b2f2eb9530.PNG)

**Comment by nigelgbanks** [comment]
The CSS issues can largely be handled by a reset style sheet to remove the quirks between browsers. I've added this to the LEAP repository.

https://github.com/livingstoneonline/LEAP-XSLT/blob/gh-pages/reset.css

But this is only the first step, in looking at the various stylesheets in the repo, they were depending on some browser defaults common to Firefox and others for example.

`<strong>Date of composition:</strong>`

Would look like this in Firefox:

<img width="248" alt="firefox" src="https://cloud.githubusercontent.com/assets/487373/20673314/89650358-b57c-11e6-8ed1-fa3d0933794e.png">

But will look like this when the reset is applied:

<img width="440" alt="reset" src="https://cloud.githubusercontent.com/assets/487373/20673335/9dcf906a-b57c-11e6-8cbe-64bcb75a2a99.png">

Because by default Firefox provides the style:

```css
strong, b {
    font-weight: bold;
}
```

So now some of those defaults must be added back in explicitly so they apply to all browsers.

**Comment by awisnicki** [comment]
OK, thank for doing this and letting me know about this issue. What would be the next step in tackling this?

**Comment by nigelgbanks** [comment]
I'm testing some fixes at the moment.

**Comment by nigelgbanks** [comment]
This has been reworked and deployed to stage & prod for review, I made some more changes to the LEAP-XSLT module to achieve this:

https://github.com/livingstoneonline/LEAP-XSLT/compare/b461df12d5931e873a2e7c343d6966e8f104c195...dd3d7f1b44d93689e1c0c426a59708b15cbb8bee

**Comment by awisnicki** [comment]
The size of text issue on this is now fixed, but on my iPhone 5, at least, when I look at the pages in portrait or landscape I still cannot scroll side to side when the text goes out of the pane.

**Comment by awisnicki** [comment]
I've realized that the side-to-side issue is also present in mobile in the manuscript viewer, not just on the multi-viewer page.

**Comment by nigelgbanks** [comment]
This should be sorted on production now.

**Comment by awisnicki** [comment]
I think the side to side issue cited here is the same one that I just described in #107 so I'm going to close this ticket. Everything else here seems resolved.
