### ISSUE TITLE
Browse by Catalogue: Sorting by Hidden Field

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#16]
Sorting by the header of a hidden field closes the table when it shouldn't.

**Comment by nigelgbanks** [comment]
I can't seem to reproduce the behaviour. The table doesn't close for me, but does re-render, when it re-renders the user will have to scroll horizontally back to the original position, since the layout can change when this happens I can't reliable auto-scroll the user to a particular horizontal position. This is a consequence of hiding the table and making it horizontally scrollable.

**Comment by awisnicki** [comment]
I just tested and it appears that the issue I describe is limited to Mozilla: the table both closes and rerenders. 

In Safari and Chrome, it just rerenders as you describe, which is fine.

**Comment by nigelgbanks** [comment]
Fix has been deployed to stage.

**Comment by awisnicki** [comment]
Looks good. Thank you.
