### ISSUE TITLE
Geolocation: Popup box

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#202]
When one clicks on a pin on the geolocation page, the font in the box that pops up is grainy. Is this the same font as use elsewhere on the site?

Also, please make the fields that appear in the box as follows: 

Location (in a slightly bigger font; Livingstone's location)
Title (hyperlinked to item)
Creator
Date

In other words, this will be similar to what we've done with the info presented for the timeline although ordering here is different and location is included.

**Comment by nigelgbanks** [comment]
Done, and I used the same settings as the timeline page.

**Comment by awisnicki** [comment]
OK, all this looks good. Please put "Title:" (not hyperlinked) before the title, and then please feel free to close out this ticket. 

Could you also tell me where the display and text of the items in the popup is edited, so I can do so myself if necessary in the future?

**Comment by nigelgbanks** [comment]
You mentioned in another ticket that you didn't see all the 3000 markers, I thought this was because when zoomed out they were overlaid overtop of one and other until you zoom in, so I've implemented a clustering system.

![screen shot 2017-10-18 at 01 36 29](https://user-images.githubusercontent.com/487373/31695837-ccab5604-b3a4-11e7-89ae-1a8aec2f1f11.png)

The unfortunate bit it is raised another issue in that often there are 50+ markers in 100% the exact same location so we can only select the top most one (this was an issue before as well, just not noticed). I'm currently looking into what can be done about this.

> OK, all this looks good. Please put "Title:" (not hyperlinked) before the title, and then please feel free to close out this ticket.

Should be sorted.

> Could you also tell me where the display and text of the items in the popup is edited, so I can do so myself if necessary in the future?

Thats a can a worms as configuring Drupal views is a wee bit complicated, there is a couple hundred settings, but the images below show only the setting for setting the title prefix.

![navigate](https://user-images.githubusercontent.com/487373/31695318-d83e4880-b3a1-11e7-99ac-b81dc1a21cd2.png)
<img width="1405" alt="settings" src="https://user-images.githubusercontent.com/487373/31695320-de7c115a-b3a1-11e7-9a3c-9eae492847be.png">
<img width="926" alt="title" src="https://user-images.githubusercontent.com/487373/31695327-e47e370e-b3a1-11e7-8b55-78f52e8faa9f.png">

**Comment by awisnicki** [comment]
OK, thanks for answering my question re: where the display/text of items is edited. That tells me what I need to know for now. Also, thanks for editing "Title." That looks good.

Re: the clustering markers, OK, just let me know what you're able to find out. My apologies that this additional issue has arisen.

**Comment by nigelgbanks** [comment]
After some exploration I found and integrated a plugin that allows use to view all the items in a single location unfortunately it doesn't work with the cluster plugin so it's one or the other, but this is the only way we can view the locations which exist right on top of one another by fanning out and drawing lines to the source. This is now deployed to stage. This is the best we can do, minus spending 20+ hours to implement our own plugin that combines the logic of the two (clustering and fanning). Surprisingly there are not many open source / shared plugins for achieving this.

![screen shot 2017-10-20 at 00 13 35](https://user-images.githubusercontent.com/487373/31798463-c4f6bed4-b52b-11e7-962f-61e8ac86356b.png)

I can push this up to production with the rest likely by Monday evening.

**Comment by awisnicki** [comment]
Honestly, I really like this. It's kind of quirky and cool, and it does get the job done well, so let's go with it. The biggest surprise for me in seeing all the locations mapped is actually how few geocoordinates we use. I thought we had a wider array, but I just checked the original MODS records and see that indeed for 3000+ items we only have 146 locations. 

The location page is a bit slow loading, but I presume it will be faster on prod?

In reviewing this, I notice one small theming issue. When you click on a pin and the box pops, up, I see that the text in the Creator and Date fields is gray. Could we have the words "Creator(s):" and "Date(s):" remain gray, but have the text that follows be black?

Other than that, this ticket is ready to be closed.

**Comment by awisnicki** [comment]
Sorry, one other thing. Right now, the default opening view is a close up of Africa:

![screen shot 2017-10-20 at 11 29 01](https://user-images.githubusercontent.com/12518623/31831722-0c2c14da-b58a-11e7-9556-00ddd7a7ecb9.png)

However, I think it would be better to zoom out one notch (which I achieved by just pushing the minus zoom one) as the opening view:

![screen shot 2017-10-20 at 11 29 03](https://user-images.githubusercontent.com/12518623/31831726-0ddb5106-b58a-11e7-803f-a4ebc988b1d9.png)

**Comment by nigelgbanks** [comment]
The zoom and font color has been handle and it's now deployed to production.

**Comment by awisnicki** [comment]
Both of these look fixed. Thank you!
