### ISSUE TITLE
Questions re: Back end menus

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#228]
The LO (icon) menu on the back end of the site has options for the "Index" and for "Flush all caches." 

The "Index" option takes one to a page called "Administration" which has a fairly self-evident purpose. It looks like this latter page is not one I'd normally be using. Could you confirm that and also sum up for me (for the site guide I'm developing) in a sentence what this page is for?

Re: "Flush all caches" would I ever use this? And, again, could you some in a sentence what this is for?

**Comment by nigelgbanks** [comment]
The index page just lists all the accessible links in the administration section of the site.

Flush all caches, clears the various server side caches (these are used to speed up the site but if changes are made the site may display "old" cached content rather than the latest changes). The sub menus are specific caches which you can clear, but if you just click on the link itself rather than a sub menu it will clear all the caches. This is something you may want to do from time to time if the content of the site looks out of date after you change something.

**Comment by awisnicki** [comment]
Ok, great. Both of these answers are quite helpful. Thank you.
