### ISSUE TITLE
Question re: Menu

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#230]
The "Management" menu appears to mirror the structure of things available from the back end of the Drupal site, but it's not quite matched up. For instance, there are some things missing here (e.g., fixed header menu and menus for all the critical editions but one) that do appear from the dropdown menus on the back end site. How does this work? What is the relationship of these two things to one another? Just to confirm, I'm talking about this: http://livingstonestage.lib.umd.edu/admin/structure/menu/manage/management plus that which is indicated in the screen shot below:
![screen shot 2017-09-28 at 15 03 08](https://user-images.githubusercontent.com/12518623/30987907-3784498c-a45e-11e7-9790-55c6c3e20906.png)

**Comment by awisnicki** [comment]
Also, can you clarify why home and site guide appear in both the Fixed Header Menu (http://livingstonestage.lib.umd.edu/admin/structure/menu/manage/menu-fixed-header-menu) and in the Secondary Menu (http://livingstonestage.lib.umd.edu/admin/structure/menu/manage/menu-secondary) pages?

**Comment by nigelgbanks** [comment]
The management menu is created by Drupal and populated by Drupal and many "contrib" modules it is not display anywhere publicly on the site.

This is the secondary menu (Front page and elsewhere):

<img width="1313" alt="secondary_menu_front" src="https://user-images.githubusercontent.com/487373/31554113-7bbee8a0-b034-11e7-9ca2-1777310bf711.png">
<img width="1182" alt="secondary_menu" src="https://user-images.githubusercontent.com/487373/31554121-807e5b96-b034-11e7-9862-d25844db7139.png">

And the fixed menu appears on the fixed header shown here:

<img width="1206" alt="fixed_header" src="https://user-images.githubusercontent.com/487373/31554126-83ed7154-b034-11e7-9c63-06a6874b2948.png">


> Also, can you clarify why home and site guide appear in both the Fixed Header Menu (http://livingstonestage.lib.umd.edu/admin/structure/menu/manage/menu-fixed-header-menu) and in the Secondary Menu (http://livingstonestage.lib.umd.edu/admin/structure/menu/manage/menu-secondary) pages?

Because they appear in both menus.

**Comment by awisnicki** [comment]
Ok, that clears all this up. Thanks again.
