### ISSUE TITLE
Setting up local FileBrowser

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#234]
Please provide basic instructions on setting up FileBrowser on my local machine, so that I can edit site files that way rather than going through the site. I've been unable to find online information for this.

**Comment by nigelgbanks** [comment]
I was to provide you with a script to allow you to sync the files down to a folder and then push them up, I can still do this, but in thinking about it I don't think it's a great idea because using such a script could allow you to quite easily erase all the those files on the server, it's probably safer for you to stick with the using the file browser on the site to upload content.

**Comment by awisnicki** [comment]
Sticking with FileBrowser on the site is no problem, and I agree with you that I'd rather not delete everything accidentally! 

However, in using FileBrowser this last week, I've come upon a few small issues which are an impediment:

1. I can only upload one file at a time. 
2. There's no way to download files. To get files, I have to go through our server. In other words, to recreate on my computer what's in Drupal (which I was hoping to do as it would make things easier in the future to maintain everything), I would have to manually get the files from the server then recreate the File Browser directory structure on my computer.
3. I don't see a way to move directories and/or files. Rather I have to delete and reupload. There's nothing like dragging from A to B.
4. I've run into an issue with swapping out files for grid and carousel. I've done this through the section page form for the given page. In some cases, it overwrites the existing file. In other cases, it adds a zero or one to my existing file name and keeps the original file. It also does this when I just try to upload the file directly to File Browser so as to overwrite the original file. When I go to delete the original file via File Browser, it tells me that the file is still in use, but it can't be because both grid and carousel are showing my new file.

Numbers 2 and 3, I can work around (and you can ignore them, unless you know an easy solution), but for numbers 1 and 4 it would be much better if they could be resolved. 

For 4, see the screen shot below for an example of the issue. IMG_5192-carousel_0.jpg (which I just added) is being used in the site in grid and carousel. The zero was added because it didn't delete the original file (IMG_5192-carousel.jpg) when I uploaded the new one, although I expected it to. I tried to delete that original file *after* I uploaded my new file, but now I'm being told that the original file is still being used in the site. However, on the site I'm seeing my new file, so I'm not sure where the original file is being used.

![screen shot 2017-11-05 at 17 22 30](https://user-images.githubusercontent.com/12518623/32420383-0aa4cc52-c24f-11e7-8bee-e13fd61ef5f0.png)

**Comment by awisnicki** [comment]
One more small snag with FileBrowser: I've just been uploading a few images for one of the section pages and see that it resizes them to 1200 on longest edge. I'd prefer that it not set a size, as I set the size before uploading.

**Comment by nigelgbanks** [comment]
The page doesn't render any images larger than 1200px wide as that's the full width of the page on the largest monitor possible, so anything larger than that wastes the users bandwidth with no visual improvement to them, I would not recommend uploading any images larger than that. That being said I've removed the scaling.

**Comment by awisnicki** [comment]
OK, image size. I didn't know that. I think in the future I'm going to have to redo the images. Right now, for an illustrative image, we have the option of clicking on it and that image in turn can be magnified, so that's where the larger size comes in. In other words, what we need, really, are two instance of each image, one for the page, the other for magnification. I'll take this issue from here.

That said, note that there is the longer set of comments above that begins "Sticking with FileBrowser...."

**Comment by nigelgbanks** [comment]
> I can only upload one file at a time.

I've added an extension that allows you to upload multiple files to a single location.

> There's no way to download files. To get files, I have to go through our server. In other words, to recreate on my computer what's in Drupal (which I was hoping to do as it would make things easier in the future to maintain everything), I would have to manually get the files from the server then recreate the File Browser directory structure on my computer.

If you double click on a file it will open a new tab that allows your to download that file. There is no batch download feature.

> I don't see a way to move directories and/or files. Rather I have to delete and reupload. There's nothing like dragging from A to B.

There isn't and it's not a supported feature of the module. Likely because moving files will break links to them in the content of pages, so no one ever implemented that functionality.

> I've run into an issue with swapping out files for grid and carousel. I've done this through the section page form for the given page. In some cases, it overwrites the existing file. In other cases, it adds a zero or one to my existing file name and keeps the original file. It also does this when I just try to upload the file directly to File Browser so as to overwrite the original file. When I go to delete the original file via File Browser, it tells me that the file is still in use, but it can't be because both grid and carousel are showing my new file.

Drupal can hold on to files for all sorts of weird reasons, though likely in this case something got messed up internally since changes were made not going through Drupal fields. Drupal assumes it has full control over the content and nothing else will make changes to it. There's not much to be done for this aside from going into the database and modifying it in each case which is a bit dangerous and error prone. I would recommend not changing or even looking at files in the folders managed by Drupal, just leave it be. Don't fuss over a number appended to the file, humans aren't really supposed to be looking at those file names.

> Numbers 2 and 3, I can work around (and you can ignore them, unless you know an easy solution), but for numbers 1 and 4 it would be much better if they could be resolved.

> For 4, see the screen shot below for an example of the issue. IMG_5192-carousel_0.jpg (which I just added) is being used in the site in grid and carousel. The zero was added because it didn't delete the original file (IMG_5192-carousel.jpg) when I uploaded the new one, although I expected it to. I tried to delete that original file after I uploaded my new file, but now I'm being told that the original file is still being used in the site. However, on the site I'm seeing my new file, so I'm not sure where the original file is being used.

Just add files through the section page and don't even bother looking at the filename or in these folders just let Drupal manage it.

**Comment by awisnicki** [comment]
Thanks very much. All this sounds good & I think FileBrowser is now setup to give me all the features I need to take things forward.
