### ISSUE TITLE
Handover

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#245]
Please merge prod (which is now exactly how we want it) down into stage and please ensure that all branches of livingstone_online_module, livingstone_online_theme, etc. are in sync. Also please be sure to back up before merging.

Please also give me some guidance on how to merge prod into stage (files, code, etc) so I can do it myself going forward.

**Comment by awisnicki** [comment]
As you're merging, please note that I'm getting the following error on prod when I add new items to Fedora.

![screenshot from 2017-12-08 10-51-18](https://user-images.githubusercontent.com/12518623/33776326-99bf3d98-dc06-11e7-8d97-d096b910b376.png)

**Comment by awisnicki** [comment]
I suspect that this is related to the error in the previous comment, but this problem arose on a separate occasion. If you look at this page, you'll see that there are three items that you can view but not download:

http://livingstoneonline.org/in-his-own-words/catalogue?f%5B0%5D=repository_ms%3A%22University%20of%20Birmingham.%20Library%22

However, I have uploaded images for all three items per the normal procedure so the camera icon should be visible here and the item images should be viewable.

**Comment by nigelgbanks** [comment]
> Please merge prod (which is now exactly how we want it) down into stage and please ensure that all branches of livingstone_online_module, livingstone_online_theme, etc. are in sync. Also please be sure to back up before merging.

Codes been set.

> Please also give me some guidance on how to merge prod into stage (files, code, etc) so I can do it myself going forward.

Same way to update production just go to the deploy tab and choose stage rather than prod. Note that this doesn't move content around just the code. The content can only be moved around manually. It's best that you work from production when creating / changing section pages and just mark them as unpublished rather than working with any content on stage directly as changes to the content will get remove during deployments etc.

> As you're merging, please note that I'm getting the following error on prod when I add new items to Fedora.

Those are just notices and warnings, the update worked (the green section above) they aren't anything to worry about.

> I suspect that this is related to the error in the previous comment, but this problem arose on a separate occasion. If you look at this page, you'll see that there are three items that you can view but not download:

> http://livingstoneonline.org/in-his-own-words/catalogue?f%5B0%5D=repository_ms%3A%22University%20of%20Birmingham.%20Library%22

> However, I have uploaded images for all three items per the normal procedure so the camera icon should be visible here and the item images should be viewable.

In this case it was a new bug not related to the warnings above that arose from a configuration change. A fix has been deployed, in the future if you do notice things are off on the browse by catalogue page you can run the "Reindex Solr" job and it should sort it, if not feel free to create a ticket.

<img width="687" alt="screen shot 2017-12-10 at 21 50 24" src="https://user-images.githubusercontent.com/487373/33809783-370f341a-ddf4-11e7-8528-29f882d774f1.png">

**Comment by awisnicki** [comment]
I do believe we're done! All looks good. Thank you so much.
