### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#246]
1) When I'm building a section page, I'd sometimes like to have the present date and/or current URL to show up in the main text. Is there a bit of code I can pop into the box for "Main Text" on the section page form to accomplish this?

2) When I'm on the Browse by Catalogue page, I scroll down to an item and open the images. Afterwards, when I close the manuscript viewer, the underlying catalogue page resets and takes me back to the top. Can I turn this off, so that the catalogue stays in the same place both before I open the viewer and after I close it?

3) When I share a page on Facebook, I'd assume it would default to the grid or carousel image, but in some cases it's random and shows an image not linked to the page at all. See screen shots below. How do I set it to default to the grid or carousel image? or is there a way to set this page by page?

![screen shot 2018-02-28 at 11 12 55](https://user-images.githubusercontent.com/12518623/36801811-ae8cd3c2-1c78-11e8-84e8-69a41d9b694d.png)

![screen shot 2018-02-28 at 11 13 14](https://user-images.githubusercontent.com/12518623/36801816-b4adab0a-1c78-11e8-8fc6-4a18c1f6cc26.png)

**Comment by nigelgbanks** [comment]
> When I'm building a section page, I'd sometimes like to have the present date and/or current URL to show up in the main text. Is there a bit of code I can pop into the box for "Main Text" on the section page form to accomplish this?

By "Present Date" do you mean the last modified date for that particular page? For Current URL do you mean a [permalink](https://en.wikipedia.org/wiki/Permalink) to the page? There really isn't a way to inject code into the page unless using javascript embedded in the "Main Text" field which wouldn't be ideal to maintain if changes are needed. Rather it would make more sense to update the display of a page to include that logic and display code in a generic way for all section pages. 

> When I'm on the Browse by Catalogue page, I scroll down to an item and open the images. Afterwards, when I close the manuscript viewer, the underlying catalogue page resets and takes me back to the top. Can I turn this off, so that the catalogue stays in the same place both before I open the viewer and after I close it?

Unfortunately not that I know of, the move actually happens when the modal opens not when it closes it's due to the following style being set on the body:

```css
.modal-open {
    overflow: hidden;
    position: fixed;
    width: 100%;
}
```

This is to ensure the viewer fits the screen fully and keeps things like scrolling etc from bleeding through to the rest of the page for example if someone were to click on the outside edge or started to scroll prior to clicking on the viewer.

> When I share a page on Facebook, I'd assume it would default to the grid or carousel image, but in some cases it's random and shows an image not linked to the page at all. See screen shots below. How do I set it to default to the grid or carousel image? or is there a way to set this page by page?

Looks like Facebook requires some additional metadata in the header to correctly identify the appropriate image.

```html
<meta property="og:image" content="URL_TO_IMAGE">
```

Otherwise it would just grab at random probably taking the order from the order the parser finds images in the page. I'll take a look into adding the logic for this.

**Comment by nigelgbanks** [comment]
The site is now generating meta tags and using the grid images where possible.

**Comment by awisnicki** [comment]
Thank you very much for looking into this!

Re: 1. For the first question, what I meant is that as part of the text on the page, I'd like to have something that says "cite this page" then given the author(s) and title (both entered manually into the section page form) followed by the date the user is accessing the page and the page URL (both displayed via some kind of underlying code). So onscreen it might display something like this and could appear anywhere in the "Main Text" field:

Adrian Wisnicki. About This Site. 5 March 2018. http://livingstoneonline.org/about-this-site/livingstone-online-introduction

The date and URL would just be automatically generated. Now that I see what you've written above, I realized I could use the UUID for permalink, but wonder if the human-readable version of the URL could be displayed instead.

Re: 2. That's too bad, but thank you for looking into this. 

Re: 3. I see the changes in Github and I just tried redeploying code to prod (just in case), but I'm still getting the same result on Facebook. See example screenshots below.

![screen shot 2018-03-05 at 11 15 13](https://user-images.githubusercontent.com/12518623/36989552-a1f8ad64-2067-11e8-8bcc-1e7652d2c105.png)
![screen shot 2018-03-05 at 11 15 56](https://user-images.githubusercontent.com/12518623/36989554-a238f626-2067-11e8-8e0d-6bd31b02385d.png)

One has the wrong screenshot still. The other doesn't have anything.

**Comment by awisnicki** [comment]
I've been looking into this more, and I think we can write off question no. 1. So that only leaves question no. 3 re: Facebook.

**Comment by nigelgbanks** [comment]
Seems to be working, although inconsistently. Sometimes Facebook fetches the image some times it does not, but when it does it gets the correct image for the given page, this is as far as we can take it.

<img width="557" alt="screen shot 2018-04-02 at 19 38 53" src="https://user-images.githubusercontent.com/487373/38210003-f4de30a6-36ad-11e8-9b00-317819a81cbe.png">
<img width="541" alt="screen shot 2018-04-02 at 19 39 57" src="https://user-images.githubusercontent.com/487373/38210004-f4f658de-36ad-11e8-88b4-8a779260db49.png">
