### ISSUE TITLE
MS Viewer: For mobile devices add "please rotate" pop-up.

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#43]

**Comment by nigelgbanks** [comment]
In playing around with this, it's nice to be able to use both orientations, in particular looking at the image looks better in portrait mode, and reading from item details / transcription looks better in landscape.

**Comment by nigelgbanks** [comment]
The latest is up on stage, try it with your phone and let me know if you find use in having access to both orientations.

**Comment by awisnicki** [comment]
So I agree with your assessment that portrait allows good viewing of image, while landscape is better for text. So here's a question. It occurs to me that one thing that might improve portrait mobile viewing of text is to reducing the padding on both sides. 
![img_3246](https://cloud.githubusercontent.com/assets/12518623/15843462/eebc5da2-2c27-11e6-945c-cfee1cafc591.PNG) In this view, Item Details could certainly be give more space at left and right. It doesn't have to be in such a narrow column. Alternately, we could do what we've done with the transcriptions and make it wider than the window -- not too wide but certainly so that more text could go on each horizontal line.

**Comment by awisnicki** [comment]
P.S. I would also suggest that, rather than flush left, each line of the icons at this level would look better centered.

**Comment by nigelgbanks** [comment]
- In portrait and landscape mode decrease margins for item details and transcription.
- In portrait and landscape mode have item details and transcription 100% wide.

Only on phone

**Comment by nigelgbanks** [comment]
Closing this ticket to combined mobile feedback to a single ticket => #55
