### ISSUE TITLE
Browse by Catalogue: Show file size for archival packages

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#51]
> In terms of downloading the packets, the sizes range from two that are just over a GB, a handful between 100 and 700 MB, and the rest below 100 MB, so I wonder if next to the download icon we couldn't put/auto-generate the file size in parenthesis just so people know what they're getting into before they download. Could you do that? So in the access column it would look like this 
> [eye icon] [download icon] (135 MB)

Should take < 1hr.

**Comment by awisnicki** [comment]
Since the icons are sort of related to this issue, I'll just put this here, but feel free to move it to a new issue if you prefer:
1. Please replace the eye icon with the camera icon: http://fontawesome.io/icon/camera/
2. Please replace the download icon with the arrow-down icon: http://fontawesome.io/icon/arrow-down/
3. Please make the restricted icon muted red (better) or gray. The bright red you've chosen stands out too much and overshadows the blue icons. Also, the tooltip on this should read "Restricted" only.

Finally, when you add the download size, you might put just a touch of padding to the right of the camera icon so that the down-arrow and the file size group together in a way that indicates that they go together.

**Comment by nigelgbanks** [comment]
Deployed to stage.

**Comment by nigelgbanks** [comment]
Set colour of text to #808080, font-size 0.8 em, and vertically center.

**Comment by nigelgbanks** [comment]
Deployed to stage.

**Comment by awisnicki** [comment]
Looks good. You may push to prod when ready!
