### ISSUE TITLE
MS Viewer: Mobile Review

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#55]
For the sake of brevity I'm combining all the mobile aspects of the viewer into a single ticket. I've made quite a few changes in the last week, some are incompatible with other choices but I feel the affect is nicer. For example when viewing in the iPhone, in portrait the icons are left aligned but in landscape they are centre aligned. Please review what's currently on stage and put any feed back in this ticket, I'm going to close the others.

**Comment by awisnicki** [comment]
Header looks fine and, in relation to mobile, I understand why you'd like to distribute the things along the top in this way. So all good.

A couple of notes:
1. Please bring the "Item Details" and "Transcriptions" buttons closer together. Make the distance between these two buttons the same as between the + magnifying glass and rotate buttons. You can take the extra space and put it to the left of the dropdown page number
2. In the search box, you should have the text "Search the entire site" in gray and the text box should be white (same as on Kathy's Amazon dev site.)
3. A couple of bugs on Filezilla: Page numbers in the dropdown are too big. Arrows and page numbers currently don't work, so you can't switch from first page to anything else.
4. I think it'd like to go with icons centered in iPhone portrait.
5. iPhone 5 portrait is wonky. Please review.

Also, one question: 
1. I thought that for portrait in iPhone etc we were going to have Images/Item Details/Transcription each be full screen? Right now it's split half and half.

**Comment by nigelgbanks** [comment]
All the above points should be addressed on stage.

**Comment by awisnicki** [comment]
Yes, everything looks good. Thank you!

I've found one last bug. Once you resolve this, you can close this ticket:

On iPhone, when I'm iPhone 5, when I'm looking first at Item Details (so only that button is highlighted) and then push the button for Transcription, the Transcription comes up (so now both buttons are highlighted).

However,  I'm looking first at Transcription (so only that button is highlighted) and then push the button for Item Details, nothing happens (so now both buttons are highlighted).

Is it possible to make it so that when both buttons are highlighted, the last of the two buttons pushed comes up?

**Comment by nigelgbanks** [comment]
I've changed it so that they toggle (only on lower resolution screens, but we can do it for large as well). So now when you click on item details it will close transcription and vice versa.

**Comment by awisnicki** [comment]
I can't check this because for some reason images aren't currently coming up in the viewer.

**Comment by nigelgbanks** [comment]
Should be sorted now.

**Comment by awisnicki** [comment]
Looks good!
