### ISSUE TITLE
Add "restricted item" link to "Browse by Catalogue" table's access column

### ISSUE THREAD

**Issue by nigelgbanks** [livingstoneonline/livingstoneonline#56]
The restricted item icon will appear for those Manuscripts which do have image content, but do not allow the user to access it. Administrators when logged in will not see this icon.

**Comment by awisnicki** [comment]
Here's a mockup of how I imagine the notification would appear in the viewer. Let me know if this is feasible/aligns with what you had in mind. The text would be controlled via a block (or something like that) so that I could modify it at will. Note also that the "contact us" bit is hyperlinked, so I'd need to be able to control that.

![restricted-item-mockup](https://cloud.githubusercontent.com/assets/12518623/16053433/623b7fb8-322e-11e6-9830-e275c3443264.png)

**Comment by nigelgbanks** [comment]
Sounds good, the only thing I'll add is that the icons related to the image viewing (zoom, rotate, page dropdown, page arrows) will be removed from the display.

**Comment by awisnicki** [comment]
No prob.

**Comment by nigelgbanks** [comment]
Ready for review.

**Comment by awisnicki** [comment]
This works as expected, so all looks good from that perspective. Thanks very much.

In terms of the text displayed: 

1) Please close up the spacing above and below the gray line so that spacing matches that on the Item Details window pane.

2) Add padding to the left and below, so that there is the same amount of padding on all four sides around the text. It doesn't look like that now.

Once you make these adjustments, you can close this ticket.

**Comment by nigelgbanks** [comment]
Changes deployed to stage.

**Comment by awisnicki** [comment]
Sorry to reopen this ticket, but it doesn't look like the padding to left and below has been added. if you take a look at my mockup up above, you'll see that it has a lot more padding around the text in general.

**Comment by nigelgbanks** [comment]
There is the same amount of padding on all sides, but it may look off in terms of an optical illusion.

<img width="1132" alt="screen shot 2016-06-16 at 18 08 25" src="https://cloud.githubusercontent.com/assets/487373/16125855/5e90b62e-33ed-11e6-9edb-cb74da2a447a.png">

**Comment by awisnicki** [comment]
Done. Thank you!
