### ISSUE TITLE
Dropdown on non-edition pages

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/livingstoneonline#97]
Just a reminder, the dropdown needs to be configured so that it does not appear on pages that are not in an edition, but to which the edition is pointing. For example:

http://livingstonestage.lib.umd.edu/spectral-imaging/notes-processed-spectral-images

That page is in the "Spectral Imaging" section (rather than being a child of the critical edition) so should not have a dropdown at top, although the critical edition dropdown does point to it.

**Comment by nigelgbanks** [comment]
K this should be sorted now, but it's important to note that the page must exists somewhere else in the top menu for this to take affect for  example it's still showing on [edition guide](http://livingstonestage.lib.umd.edu/edition-guide) but that's because it's not yet been placed elsewhere in the [topmenu](http://livingstonestage.lib.umd.edu/admin/structure/menu/manage/menu-topmenu).

**Comment by awisnicki** [comment]
OK, this looks sorted. Thank you! Closing this ticket.
